#!/bin/bash

set -e

# Google Cloud project details
PROJECT_ID="your-gcp-project-id"
CLUSTER_NAME="your-cluster-name"
CLUSTER_ZONE="your-cluster-zone"
NAMESPACE="your-kubernetes-namespace"

# Authenticate to GCP and get GKE credentials
gcloud auth activate-service-account --key-file /path/to/your-service-account-key.json
gcloud config set project $PROJECT_ID
gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE --project $PROJECT_ID

# Function to update Kubernetes deployment
update_k8s_deployment() {
    API_NAME=$1
    IMAGE_TAG=$2
    CONTAINER_REGISTRY="gcr.io/$PROJECT_ID"

    echo "Updating Kubernetes deployment for $API_NAME to use image tag $IMAGE_TAG"

    kubectl set image deployment/$API_NAME $API_NAME=$CONTAINER_REGISTRY/$API_NAME:$IMAGE_TAG -n $NAMESPACE
}

# Read the image tags from the file
if [ -f /tmp/deploy_images.txt ]; then
    while read line; do
        API_NAME=$(echo $line | cut -d' ' -f1)
        IMAGE_TAG=$(echo $line | cut -d' ' -f2)
        update_k8s_deployment $API_NAME $IMAGE_TAG
    done < /tmp/deploy_images.txt
else
    echo "No image tags found to deploy."
fi

echo "GKE deployment completed successfully."

#!/bin/bash

set -e

# Define project and namespace
NAMESPACE="your-kubernetes-namespace"

# Function to update Kubernetes deployment
update_k8s_deployment() {
    DEPLOYMENT_NAME=$1
    IMAGE_NAME=$2
    IMAGE_TAG=$3
    CONTAINER_REGISTRY="nexus3.systems.uk.hsbc:18080/goatech-fds"

    echo "Updating Kubernetes deployment $DEPLOYMENT_NAME to use image $IMAGE_NAME:$IMAGE_TAG"

    kubectl set image deployment/$DEPLOYMENT_NAME $IMAGE_NAME=$CONTAINER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG -n $NAMESPACE
}

# Read the deploy_images.txt file and update the deployments
while IFS= read -r line; do
    API_NAME=$(echo $line | cut -d' ' -f1)
    IMAGE_TAG=$(echo $line | cut -d' ' -f2)

    case $API_NAME in
        "aggregate-api")
            update_k8s_deployment "deployment-aggregate-api" "$API_NAME" "$IMAGE_TAG"
            ;;
        "filenet-api")
            for i in {1..5}; do
                update_k8s_deployment "deployment-filenetapi-$i" "$API_NAME" "$IMAGE_TAG"
            done
            ;;
        "arc-api")
            update_k8s_deployment "deployment-arcapi" "$API_NAME" "$IMAGE_TAG"
            ;;
        "seeker-ui")
            update_k8s_deployment "deployment-seekerui" "$API_NAME" "$IMAGE_TAG"
            ;;
        *)
            echo "Unknown API name: $API_NAME"
            ;;
    esac
done < /tmp/deploy_images.txt

echo "All deployments updated successfully."


# Read the deploy_images.txt file
if [ ! -f /tmp/deploy_images.txt ]; then
    echo "No images to deploy. Exiting."
    exit 0
fi

while read -r line; do
    API_NAME=$(echo $line | awk '{print $1}')
    IMAGE_TAG=$(echo $line | awk '{print $2}')

    echo "Updating Kubernetes deployment for $API_NAME to use image $API_NAME:$IMAGE_TAG"

    if [ "$API_NAME" == "aggregate-api" ]; then
        kubectl set image deployment/deployment-aggregate-api aggregate-api=$CONTAINER_REGISTRY/$API_NAME:$IMAGE_TAG
        echo "deployment.apps/deployment-aggregate-api image updated"
    elif [[ "$API_NAME" == "filenet-api" ]]; then
        for i in {1..5}; do
            kubectl set image deployment/deployment-filenetapi-$i filenetapi-$i=$CONTAINER_REGISTRY/$API_NAME:$IMAGE_TAG
            echo "deployment.apps/deployment-filenetapi-$i image updated"
        done
    elif [ "$API_NAME" == "arc-api" ]; then
        kubectl set image deployment/deployment-arc-api arc-api=$CONTAINER_REGISTRY/$API_NAME:$IMAGE_TAG
        echo "deployment.apps/deployment-arc-api image updated"
    else
        echo "Unknown API_NAME: $API_NAME. Skipping."
    fi
done < /tmp/deploy_images.txt

echo "All Kubernetes deployments updated successfully."
