name: "Create PR"

on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - chore/*
      - feat/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly grant write permissions to GITHUB_TOKEN
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        id: create_pr
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: Merge ${{ steps.extract_branch.outputs.branch_name }} into master
          PULL_REQUEST_BODY: |
            This PR was automatically created by the GitHub Actions workflow.
            It merges changes from branch `${{ steps.extract_branch.outputs.branch_name }}` into `main`.
          PULL_REQUEST_BASE: main
          PULL_REQUEST_ASSIGNEES: ${{ github.actor }}
          PULL_REQUEST_DRAFT: true

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          service_account: 'sa-git-hub@sharp-agent-457306-d5.iam.gserviceaccount.com'
      - id: get-gke-credentials
        uses: google-github-actions/get-gke-credentials@v0.4.0
        with:
          cluster_name: cluster-1
          location: us-central1-c
      
      - id: get-pods
        run: kubectl get pods
