name: "Create PR"

on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - chore/*
      - feat/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly grant write permissions to GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        id: create_pr
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: Merge ${{ steps.extract_branch.outputs.branch_name }} into master
          PULL_REQUEST_BODY: |
            This PR was automatically created by the GitHub Actions workflow.
            It merges changes from branch `${{ steps.extract_branch.outputs.branch_name }}` into `main`.
          PULL_REQUEST_BASE: main
          PULL_REQUEST_ASSIGNEES: ${{ github.actor }}
          PULL_REQUEST_DRAFT: true
