name: "CI Workflow for Microservices"

on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - chore/*
      - feat/*
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout code
        uses: actions/checkout@v4   
      - name: Create Pull Request
        id: create_pr
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.OWNER_TOKEN }}
          PASS_ON_ERROR: true
          PULL_REQUEST_UPDATE: true
          PULL_REQUEST_TITLE: Merge ${{ github.ref_name }} into master
          PULL_REQUEST_BODY: |
            This PR was automatically created by the GitHub Actions workflow.
            It merges changes from branch `${{ github.ref_name }}` into `main`.
          PULL_REQUEST_BASE: main
          PULL_REQUEST_ASSIGNEES: ${{ github.actor }}
          PULL_REQUEST_DRAFT: true

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: SSH into GCP VM and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            echo "🔹 Connected to VM!"
            kubectl get nodes
            kubectl get po

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: access_token
          workload_identity_provider: 'projects/327406114637/locations/global/workloadIdentityPools/github-identity-pool/providers/github'
          service_account: 'sa-git-hub@careful-acumen-466410-f0.iam.gserviceaccount.com'

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get short commit ID
        id: get-tag
        run: |
          echo "commit_id=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Check for changes in source code
        id: check-changes
        run: |
          git diff --quiet HEAD^ HEAD ./src || echo "changes_detected=true" >> $GITHUB_ENV

      - name: Loop through microservices
        if: env.changes_detected == 'true'
        run: |
          for service in adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice; do
            # Build and push Docker image
            docker build -t us-central1-docker.pkg.dev/sharp-agent-457306-d5/hipster/$service:${{ env.commit_id }} ./$service
            docker push us-central1-docker.pkg.dev/sharp-agent-457306-d5/hipster/$service:${{ env.commit_id }}
            
            # Update Kubernetes manifest
            sed -i "s|image: .*|image: us-central1-docker.pkg.dev/sharp-agent-457306-d5/hipster/$service:${{ env.commit_id }}|" ./k8s/$service.yaml
          done

      - name: Commit and push updated manifests
        if: env.changes_detected == 'true'
        run: |
          git config user.name "Hackathon Bot"
          git config user.email "hackathon-bot@sharp-agent.com"
          git add ./k8s/*.yaml
          git commit -m "Update Kubernetes manifests with new image tags"
          git push origin ${{ github.ref_name }}
