name: "Create PR"

on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - chore/*
      - feat/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Explicitly grant write permissions to GITHUB_TOKEN
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: ${{ github.ref_name }}
          title: "Automated PR for branch ${{ github.ref_name }}"
          body: "This pull request was automatically created for branch ${{ github.ref_name }}."
          token: ${{ secrets.GITHUB_TOKEN }}
